language: node_js

node_js:
  - "7"
  
notifications:
  email: false

cache:
  directories:
    - "node_modules"

scripts:
  - npm run test --silent

after_success: 
  - npm run coverage

deploy:
  provider: npm
  email: "hello@salieo.com"
  api_key: $NPM_TOKEN
  on:
    tags: true